Added Channel#set_options and Channel#options= aliases
ably/ably-ruby pull request #326
Opened 2021-09-16 20:34 UTC by lukaszsliwa

Resolves #271 

`Channel#set_options` (RSL7) was implemented as `Channel#update_options`.
Added aliases: `Channel#options=` and `Channel#set_options`

2021-09-20 15:06 UTC, owenpearson approved these changes
LGTM, thanks

2021-09-20 15:12 UTC, owenpearson requested changes
Actually, I'm not 100% sure on this. @lukaszsliwa What's the reason for the second alias? And can we emit a deprecation warning for people using `update_options` so that we can give people a chance to migrate to `set_options` and then we can remove `update_options` in the next major release.

2021-09-20 15:32 UTC, lukaszsliwa commented
> Actually, I'm not 100% sure on this. @lukaszsliwa What's the reason for the second alias? And can we emit a deprecation warning for people using `update_options` so that we can give people a chance to migrate to `set_options` and then we can remove `update_options` in the next major release.

I added second alias  because it is more natural for ruby but spec says that it should be `set_options`.

2021-09-20 15:37 UTC, TheSmartnik approved these changes
While `set_options` isn't very rubyish it adheres to the doc and `options=` is an idiomatic ruby method. We do add aliases purely for convenience so I guess it's a good idea

2021-09-27 15:04 UTC, owenpearson approved these changes

2021-09-27 15:04 UTC, merged