Update RSC7
ably/ably-ruby pull request #334
Opened 2021-11-08 16:01 UTC by TheSmartnik

Fixes https://ably.atlassian.net/browse/SDK-1084

Well, everything turned out to be already working :D So, I've just updated the specs

2021-11-08 16:07 UTC, TheSmartnik commented
Oh, it also fixes https://ably.atlassian.net/browse/SDK-1085

Three lines, two tickets

2021-11-15 15:47 UTC, owenpearson requested changes

2021-11-15 15:47 UTC, owenpearson commented on lib/ably/version.rb
> +  PROTOCOL_VERSION = '1.2'
As discussed at the previous standup we're not at API version 1.2 yet so I don't agree with this change.

2022-02-22 16:59 UTC, lukaszsliwa approved these changes

2022-03-15 20:15 UTC, owenpearson approved these changes

2022-03-31 12:01 UTC, merged