Max message size fix
ably/ably-ruby pull request #382
Opened 2022-10-03 13:41 UTC by owenpearson

2022-10-03 16:23 UTC, lukaszsliwa approved these changes

2022-10-03 18:40 UTC, QuintinWillison requested changes
I see we're mostly removing code here.

What I can't see is _why_ we're making this change. There is no opening comment on this pull request that explains to reviewers or those looking back in future why the change is being made. Even the [single commit](https://github.com/ably/ably-ruby/pull/382/commits/e2764e6c08c04f733109abdcdc929b3602555218) only contains a single line:

> fix: remove inbound max_message_size check

which pretty much matches the pull request title:

> fix: remove inbound message size validation

What I would like to see, one or more of:

- Opening comment explaining why the change is being made (i.e. what is wrong in the current implementation)
- A `bug` label assigned to ensure it makes it into the changelog as such
- A link to a GitHub issue that is `bug` labelled, describing the problem with the current implementation
- A link from this PR, or the linked GitHub issue, to other sources of information ... e.g. an " (internal)"-suffixed link to a Slack thread, perhaps

2022-10-04 09:37 UTC, owenpearson commented
Good point @QuintinWillison, I've updated the description now

2022-10-04 09:39 UTC, QuintinWillison approved these changes

2022-10-04 09:41 UTC, merged