rest/channel_spec: fix test checking error messages
ably/ably-ruby pull request #422
Opened 2024-07-02 15:33 UTC by Zariel

Replace error message checks with error code checks. Error messages are not guaranteed to be consistent across versions/systems but the error codes are.

2024-07-02 16:20 UTC, lmars approved these changes
LGTM

2024-07-03 10:32 UTC, sacOO7 approved these changes
lgtm

2024-07-03 11:10 UTC, sacOO7 requested changes
Some of the acceptance tests are failing, can you take a look @Zariel

2024-07-04 10:09 UTC, jamienewcomb commented
@sacOO7 can you approve and merge this if you are happy please

2024-07-04 12:09 UTC, sacOO7 commented
@Zariel I assume changes are fixed on the sandbox and will not break at client side going forward right?

2024-07-04 12:43 UTC, sacOO7 commented on spec/acceptance/rest/channel_spec.rb
> +                expect { channel.publish([name: 'event', client_id: 'invalid']) }.to raise_error Ably::Exceptions::InvalidRequest, /40012/
```suggestion
                expect { channel.publish([name: 'event', client_id: 'invalid']) }.to raise_error(Ably::Exceptions::InvalidRequest, /40012/)
```

2024-07-04 17:17 UTC, sacOO7 approved these changes
lgtm

2024-07-04 18:01 UTC, merged